name: learn artifact 1a

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-on-windows:
    runs-on: windows-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSVC compiler
      # uses: microsoft/setup-msbuild@v1.0.2
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: CMake configure
      run: cmake --preset Ninja-Msvc-Debug
      
    - name: CMake build
      run: cmake --build --preset Ninja-Msvc-Debug

    - name: CMake run
      run: cmake --build --preset Ninja-Msvc-Debug --target run

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary file
        path: buildNinja/Msvc/buildOut/StarterProject/bin/Debug/*.exe

    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: binary file
