name: Build and run without CMakePresets.json 2

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  singleConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compilerCpp: 
          - name: g++
            buildSubDir: Gnu
          - name: clang++
            buildSubDir: Clang
          - name: cl
            buildSubDir: Msvc
        buildType: [Debug, Release]
        generator: 
          - name: Ninja
            buildDir: buildNinja
          - name: "Unix Makefiles"
            buildDir: buildMake
          - name: "NMake Makefiles"
            buildDir: buildMake

        exclude:
          - os: ubuntu-latest
            compilerCpp: 
              name: cl
          - os: ubuntu-latest
            generator: 
              name: "NMake Makefiles"

          - os: macos-latest
            compilerCpp: 
              name: cl
          - os: macos-latest
            compilerCpp:
              name: g++
          - os: macos-latest
            generator: 
              name: "NMake Makefiles"

          - os: windows-latest
            compilerCpp: 
              name: g++
          - os: windows-latest
            compilerCpp: 
              name: clang++
          - os: windows-latest
            generator: 
              name: "Unix Makefiles"

    runs-on: ${{matrix.os}}

    steps:
    - run: echo Platform = ${{matrix.os}}, compiler = ${{matrix.compilerCpp}}, build type = ${{matrix.buildType}}

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Location of repo
      run: |
        pwd 
        ls ${{github.workspace}}
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup MSVC compiler
      if: ${{matrix.os == 'windows-latest'}}
      # uses: microsoft/setup-msbuild@v1.0.2
      uses: ilammy/msvc-dev-cmd@v1

    - name: MSVC compiler version
      if: ${{matrix.os == 'windows-latest'}}
      shell: bash
      run: |
        echo cl
        cl

    - name: Tool versions
      shell: bash
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: >
        CMake configure ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}
      run: > 
        cmake -S . 
        -B ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -G "${{matrix.generator.name}}" 
        -D CMAKE_BUILD_TYPE=${{matrix.buildType}} 
        -D CMAKE_CXX_COMPILER=${{matrix.compilerCpp.name}}
      
    - name: >
        CMake build ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8

    - name: >
        CMake run ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}  
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --target run


  multiConfig:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        compilerCpp: 
          - name: g++
            buildSubDir: Gnu
          - name: clang++
            buildSubDir: Clang
          - name: cl
            buildSubDir: Msvc
        buildType: [Debug, Release]
        generator: 
          - name: "Ninja Multi-Config"
            buildDir: buildNinjaMC
          - name: Xcode
            buildDir: buildXcode

        exclude:
          - os: ubuntu-latest
            compilerCpp: 
              name: cl
          - os: ubuntu-latest
            generator: 
              name: Xcode

          - os: macos-latest
            compilerCpp: 
              name: cl
          - os: macos-latest
            compilerCpp:
              name: g++

          - os: windows-latest
            compilerCpp: 
              name: g++
          - os: windows-latest
            compilerCpp: 
              name: clang++
          - os: windows-latest
            generator: 
              name: Xcode

    runs-on: ${{matrix.os}}

    steps:
    - run: echo Platform = ${{matrix.os}}, compiler = ${{matrix.compilerCpp}}, build type = ${{matrix.buildType}}

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Location of repo
      run: |
        pwd 
        ls ${{github.workspace}}
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup MSVC compiler
      if: ${{matrix.os == 'windows-latest'}}
      # uses: microsoft/setup-msbuild@v1.0.2
      uses: ilammy/msvc-dev-cmd@v1

    - name: MSVC compiler version
      if: ${{matrix.os == 'windows-latest'}}
      shell: bash
      run: |
        echo cl
        cl

    - name: Tool versions
      shell: bash
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: >
        CMake configure ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}
      run: > 
        cmake -S . 
        -B ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -G "${{matrix.generator.name}}" 
        -D CMAKE_CXX_COMPILER=${{matrix.compilerCpp.name}}
      
    - name: >
        CMake build ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}

    - name: >
        CMake run ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}  
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}
        --target run


  multiArchitecture:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        compilerCpp: 
          - name: cl
            buildSubDir: Msvc
        buildType: [Debug, Release]
        generator: 
          - name: Visual Studio 17 2022
            buildDir: buildVS
        architecture:
          - name: win32
            buildSubDir: x32
          - name: x64
            buildSubDir: x64

    runs-on: ${{matrix.os}}

    steps:
    - run: echo Platform = ${{matrix.os}}, compiler = ${{matrix.compilerCpp}}, build type = ${{matrix.buildType}} architecture = ${{matrix.architecture.name}}

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Location of repo
      run: |
        pwd 
        ls ${{github.workspace}}
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Setup MSVC compiler
      # uses: microsoft/setup-msbuild@v1.0.2
      uses: ilammy/msvc-dev-cmd@v1

    - name: MSVC compiler version
      # if: ${{matrix.os == 'windows-latest'}}
      shell: bash
      run: |
        echo cl
        cl

    - name: Tool versions
      shell: bash
      run: | 
        echo cmake --version
        cmake --version

    - name: >
        CMake configure ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}} ~
        architecture = ${{matrix.compilerCpp.architecture.name}} ~
      run: > 
        cmake -S . 
        -B ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -G "${{matrix.generator.name}}" 
        -A ${{matrix.architecture.name}}
      
    - name: >
        CMake build ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}

    - name: >
        CMake run ~ 
        platform = ${{runner.os}} ~ 
        generator = ${{matrix.generator.name}} ~ 
        build type = ${{matrix.buildType}} ~ 
        compiler = ${{matrix.compilerCpp.name}}  
      run: > 
        cmake 
        --build ${{matrix.generator.buildDir}}/${{matrix.architecture.buildSubDir}}/${{matrix.compilerCpp.buildSubDir}} 
        -j8 
        --config ${{matrix.buildType}}
        --target run
