name: Build and run without CMakePresets.json

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Location of repo
      run: |
        pwd 
        ls ${{ github.workspace }}
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: CMake configure, build, run on (Linux, Ninja, Gnu, Debug)
      run: |
        cmake --preset Ninja-Gnu-Debug
        cmake --build --preset Ninja-Gnu-Debug
        cmake --build --preset Ninja-Gnu-Debug --target run

    - name: CMake configure, build, run on (Linux, Ninja, Gnu, Release)
      run: |
        cmake --preset Ninja-Gnu-Release
        cmake --build --preset Ninja-Gnu-Release
        cmake --build --preset Ninja-Gnu-Release --target run

    - name: CMake configure, build, run on (Linux, Ninja, Clang, Debug)
      run: |
        cmake --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug --target run

    - name: CMake configure, build, run on (Linux, Ninja, Clang, Release)
      run: |
        cmake --preset Ninja-Clang-Release
        cmake --build --preset Ninja-Clang-Release
        cmake --build --preset Ninja-Clang-Release --target run

    - name: CMake configure, build, run on (Linux, Make, Gnu, Debug)
      run: |
        cmake --preset Make-Gnu-Debug
        cmake --build --preset Make-Gnu-Debug
        cmake --build --preset Make-Gnu-Debug --target run

    - name: CMake configure, build, run on (Linux, Make, Gnu, Release)
      run: |
        cmake --preset Make-Gnu-Release
        cmake --build --preset Make-Gnu-Release
        cmake --build --preset Make-Gnu-Release --target run

    - name: CMake configure, build, run on (Linux, Make, Clang, Debug)
      run: |
        cmake --preset Make-Clang-Debug
        cmake --build --preset Make-Clang-Debug
        cmake --build --preset Make-Clang-Debug --target run

    - name: CMake configure, build, run on (Linux, Make, Clang, Release)
      run: |
        cmake --preset Make-Clang-Release
        cmake --build --preset Make-Clang-Release
        cmake --build --preset Make-Clang-Release --target run



  build-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Location of repo
      run: |
        pwd 
        ls ${{ github.workspace }}
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      run: | 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: CMake configure, build, run on (MacOS, Ninja, Clang, Debug)
      run: |
        cmake --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug
        cmake --build --preset Ninja-Clang-Debug --target run

    - name: CMake configure, build, run on (MacOS, Ninja, Clang, Release)
      run: |
        cmake --preset Ninja-Clang-Release
        cmake --build --preset Ninja-Clang-Release
        cmake --build --preset Ninja-Clang-Release --target run

    - name: CMake configure, build, run on (MacOS, Make, Clang, Debug)
      run: |
        cmake --preset Make-Clang-Debug
        cmake --build --preset Make-Clang-Debug
        cmake --build --preset Make-Clang-Debug --target run

    - name: CMake configure, build, run on (MacOS, Make, Clang, Release)
      run: |
        cmake --preset Make-Clang-Release
        cmake --build --preset Make-Clang-Release
        cmake --build --preset Make-Clang-Release --target run


  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Location of repo
      run: |
        pwd 
        ls ${{ github.workspace }} -Name

    - name: Setup MSVC compiler
      # uses: microsoft/setup-msbuild@v1.0.2
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: powershell
      run: |
        Write-Host cl
        cl

        Write-Host 
        Write-Host cmake --version
        cmake --version

        Write-Host 
        Write-Host ninja --version
        ninja --version

    - name: CMake configure, build, run on (Windows, Ninja, Msvc, Debug)
      run: |
        cmake --preset Ninja-Msvc-Debug
        cmake --build --preset Ninja-Msvc-Debug
        cmake --build --preset Ninja-Msvc-Debug --target run

    - name: CMake configure, build, run on (Windows, Ninja, Msvc, Release)
      run: |
        cmake --preset Ninja-Msvc-Release
        cmake --build --preset Ninja-Msvc-Release
        cmake --build --preset Ninja-Msvc-Release --target run

    - name: CMake configure, build, run on (Windows, NMake, Msvc, Debug)
      run: |
        cmake --preset NMake-Msvc-Debug
        cmake --build --preset NMake-Msvc-Debug
        cmake --build --preset NMake-Msvc-Debug --target run

    - name: CMake configure, build, run on (Windows, NMake, Msvc, Release)
      run: |
        cmake --preset NMake-Msvc-Release
        cmake --build --preset NMake-Msvc-Release
        cmake --build --preset NMake-Msvc-Release --target run
