name: Build and run without CMakePresets.json

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Location of repo
      run: |
        pwd 
        ls ${{ github.workspace }}
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      run: | 
        echo g++ --version
        g++ --version
        echo 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: CMake configure, build, run --- Linux, Make, Gnu, Debug
      run: |
        cmake -S . -B buildMake_/Gnu -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=g++
        cmake --build buildMake_/Gnu -j8
        cmake --build buildMake_/Gnu -j8 --target run

    - name: CMake configure, build, run --- Linux, Make, Gnu, Release
      run: |
        cmake -S . -B buildMake_/Gnu -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=g++
        cmake --build buildMake_/Gnu -j8
        cmake --build buildMake_/Gnu -j8 --target run

    - name: CMake configure, build, run --- Linux, Make, Clang, Debug
      run: |
        cmake -S . -B buildMake_/Clang -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=clang++
        cmake --build buildMake_/Clang -j8
        cmake --build buildMake_/Clang -j8 --target run

    - name: CMake configure, build, run --- Linux, Make, Clang, Release
      run: |
        cmake -S . -B buildMake_/Clang -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=clang++
        cmake --build buildMake_/Clang -j8
        cmake --build buildMake_/Clang -j8 --target run

    - name: CMake configure, build, run --- Linux, Ninja, Gnu, Debug
      run: |
        cmake -S . -B buildNinja_/Gnu -G Ninja -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=g++
        cmake --build buildNinja_/Gnu -j8
        cmake --build buildNinja_/Gnu -j8 --target run

    - name: CMake configure, build, run --- Linux, Ninja, Gnu, Release
      run: |
        cmake -S . -B buildNinja_/Gnu -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=g++
        cmake --build buildNinja_/Gnu -j8
        cmake --build buildNinja_/Gnu -j8 --target run
        
    - name: CMake configure, build, run --- Linux, Ninja, Clang, Debug
      run: |
        cmake -S . -B buildNinja_/Clang -G Ninja -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=clang++
        cmake --build buildNinja_/Clang -j8
        cmake --build buildNinja_/Clang -j8 --target run

    - name: CMake configure, build, run --- Linux, Ninja, Clang, Release
      run: |
        cmake -S . -B buildNinja_/Clang -G Ninja -D CMAKE_BUILD_TYPE=Release -D CMAKE_CXX_COMPILER=clang++
        cmake --build buildNinja_/Clang -j8
        cmake --build buildNinja_/Clang -j8 --target run

    - name: CMake configure, build, run --- Linux, Ninja Multi-Config, Gnu, Debug & Release
      run: |
        cmake -S . -B buildNinjaMC_/Gnu -G "Ninja Multi-Config" -D CMAKE_CXX_COMPILER=g++
        cmake --build buildNinjaMC_/Gnu -j8 --config Debug --target run
        cmake --build buildNinjaMC_/Gnu -j8 --config Release --target run

    - name: CMake configure, build, run --- Linux, Ninja Multi-Config, Clang, Debug & Release
      run: |
        cmake -S . -B buildNinjaMC_/Clang -G "Ninja Multi-Config" -D CMAKE_CXX_COMPILER=clang++
        cmake --build buildNinjaMC_/Clang -j8 --config Debug --target run
        cmake --build buildNinjaMC_/Clang -j8 --config Release --target run


  build-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Location of repo
      run: |
        pwd 
        ls ${{ github.workspace }}
        
    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      run: | 
        echo clang++ --version
        clang++ --version
        echo 
        echo cmake --version
        cmake --version
        echo 
        echo ninja --version
        ninja --version

    - name: CMake configure, build, run --- MacOS, Make, Clang, Debug
      run: |
        cmake -S . -B buildMake_ -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Debug
        cmake --build buildMake_ -j8
        cmake --build buildMake_ -j8 --target run

    - name: CMake configure, build, run --- MacOS, Make, Clang, Release
      run: |
        cmake -S . -B buildMake_ -G "Unix Makefiles" -D CMAKE_BUILD_TYPE=Release
        cmake --build buildMake_ -j8
        cmake --build buildMake_ -j8 --target run

    - name: CMake configure, build, run --- MacOS, Ninja, Msvc, Debug
      run: |
        cmake -S . -B buildNinja_ -G Ninja -D CMAKE_BUILD_TYPE=Debug
        cmake --build buildNinja_ -j8
        cmake --build buildNinja_ -j8 --target run

    - name: CMake configure, build, run --- MacOS, Ninja, Clang, Release
      run: |
        cmake -S . -B buildNinja_ -G Ninja -D CMAKE_BUILD_TYPE=Release
        cmake --build buildNinja_ -j8
        cmake --build buildNinja_ -j8 --target run

    - name: CMake configure, build, run --- MacOS, Ninja Multi-Config, Clang, Debug & Release
      run: |
        cmake -S . -B buildNinjaMC_ -G "Ninja Multi-Config"
        cmake --build buildNinjaMC_ -j8 --config Debug --target run
        cmake --build buildNinjaMC_ -j8 --config Release --target run

    - name: CMake configure, build, run --- MacOS, Xcode, Clang, Debug & Release
      run: |
        cmake -S . -B buildXcode_ -G Xcode
        cmake --build buildXcode_ -j8 --config Debug --target run
        cmake --build buildXcode_ -j8 --config Release --target run


  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Location of repo
      run: |
        pwd 
        ls ${{ github.workspace }} -Name

    - name: Setup MSVC compiler
      # uses: microsoft/setup-msbuild@v1.0.2
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Tool versions
      shell: powershell
      run: |
        Write-Host cl
        cl

        Write-Host 
        Write-Host cmake --version
        cmake --version

        Write-Host 
        Write-Host ninja --version
        ninja --version

    - name: CMake configure, build, run --- Windows, NMake, Msvc, Debug
      run: |
        cmake -S . -B buildNMake_ -G "NMake Makefiles" -D CMAKE_BUILD_TYPE=Debug -D CMAKE_CXX_COMPILER=cl.exe
        cmake --build buildNMake_
        cmake --build buildNMake_ --target run

    - name: CMake configure, build, run --- Windows, NMake, Msvc, Release
      run: |
        cmake -S . -B buildNMake_ -G "NMake Makefiles" -D CMAKE_BUILD_TYPE=Release
        cmake --build buildNMake_
        cmake --build buildNMake_ --target run

    - name: CMake configure, build, run --- Windows, Ninja, Msvc, Debug
      run: |
        cmake -S . -B buildNinja_ -G Ninja -D CMAKE_BUILD_TYPE=Debug
        cmake --build buildNinja_ -j8
        cmake --build buildNinja_ -j8 --target run

    - name: CMake configure, build, run --- Windows, Ninja, Msvc, Release
      run: |
        cmake -S . -B buildNinja_ -G Ninja -D CMAKE_BUILD_TYPE=Release
        cmake --build buildNinja_ -j8
        cmake --build buildNinja_ -j8 --target run

    - name: CMake configure, build, run --- Windows, Ninja Multi-Config, Msvc, Debug & Release
      run: |
        cmake -S . -B buildNinjaMC_ -G "Ninja Multi-Config"
        cmake --build buildNinjaMC_ -j8 --config Debug --target run
        cmake --build buildNinjaMC_ -j8 --config Release --target run

    - name: CMake configure, build, run --- Windows, Visual Studio win32, Msvc, Debug & Release
      run: |
        cmake -S . -B buildVS_/x32 -G "Visual Studio 17 2022" -A win32
        cmake --build buildVS_/x32 -j8 --config Debug --target run
        cmake --build buildVS_/x32 -j8 --config Release --target run

    - name: CMake configure, build, run --- Windows, Visual Studio x64, Msvc, Debug & Release
      run: |
        cmake -S . -B buildVS_/x64 -G "Visual Studio 17 2022" -A x64
        cmake --build buildVS_/x64 -j8 --config Debug --target run
        cmake --build buildVS_/x64 -j8 --config Release --target run
