name: Show env

on:
  push:
    branches:
      - '*'
      
env:
  somevar: 'lastvar'
jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Is variable exported?
        run: |
          echo "${{ env.somevar }}"
          echo "action_state=yellow" >> $GITHUB_ENV
      # - name: PowerShell script
      #   # You may pin to the exact commit or the version.
      #   # uses: Amadevus/pwsh-script@25a636480c7bc678a60bbf4e3e5ac03aca6cf2cd
      #   uses: Amadevus/pwsh-script@v2.0.0
      #   continue-on-error: true
      #   with: 
      #     # PowerShell script to execute in Actions-hydrated context
      #     script: | 
      #       Write-Host $env:somevar
      #       Write-Host $env:action_state
      - name: Read exported variable
        run: |
          echo "$action_state"
          echo "${{ env.action_state }}"