name: Test CI - Multi-Line Value
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Defining a new Environment Variable
        run: |                          
          MULTI_LINES_TEXT="this is line one \n
                            this is line two \n
                            this is line three \n"    

          echo "MULTI_LINES_TEXT_ENV_VAR<<EOF" >> $GITHUB_ENV
          # here we can place the command that will generate multi-line text
          echo $MULTI_LINES_TEXT >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
          
      - name: Using the previously defined environment variable
        run: |
          echo ${{ env.ONE_LINE_TEXT_ENV_VAR }}

      - name: test
        id: plan
        shell: bash
        run: |
          out="hello \n world"
          echo "out=$out" >> $GITHUB_OUTPUT
