name: Check exclude

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
        version: [12, 14, 16]
        environment: [staging, production]
        exclude:
          - os: macos-latest
            version: 12
            environment: production
          - os: windows-latest
            version: 16

    runs-on: ${{ matrix.os }}

    steps:
      - run: os = ${{ matrix.os }}, version = ${{ matrix.version}}, environment = ${{ matrix.environment }}
